[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
OptimizationOptimJL = "36348300-93cb-4f02-beb5-3c3902f8871e"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
